/**
 * A small curated pack of well-known memory verses (spec section 4's examples plus other
 * widely-memorized passages), bundled in two public-domain translations so the app never
 * needs a network call or a licensed Bible-text API to have something to add on day one.
 *
 * IMPORTANT: this text was transcribed from the model's training knowledge, not copied
 * from a verified source file. KJV wording is extremely stable and high-confidence; the
 * WEB (World English Bible) wording is lower-confidence. Before relying on this pack for
 * real memorization, spot-check it against a source such as ebible.org/web or
 * biblegateway.com (both freely license KJV/WEB) and correct any drift — the Add Verse
 * screen's manual-entry path exists specifically so wrong bundled text is never a dead end.
 */
export interface StarterVerse {
  book: string
  chapter: number
  verseStart: number
  verseEnd: number
  kjvText: string
  webText: string
}

export function starterVerseReference(v: StarterVerse): string {
  return v.verseStart === v.verseEnd ? `${v.book} ${v.chapter}:${v.verseStart}` : `${v.book} ${v.chapter}:${v.verseStart}-${v.verseEnd}`
}

export const starterVersePack: StarterVerse[] = [
  { book: 'John', chapter: 3, verseStart: 16, verseEnd: 16,
    kjvText: 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.',
    webText: 'For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.' },
  { book: 'Romans', chapter: 8, verseStart: 28, verseEnd: 28,
    kjvText: 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.',
    webText: 'We know that all things work together for good for those who love God, for those who are called according to his purpose.' },
  { book: 'Psalm', chapter: 119, verseStart: 105, verseEnd: 105,
    kjvText: 'Thy word is a lamp unto my feet, and a light unto my path.',
    webText: 'Your word is a lamp to my feet, and a light for my path.' },
  { book: 'Colossians', chapter: 3, verseStart: 16, verseEnd: 16,
    kjvText: 'Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord.',
    webText: 'Let the word of Christ dwell in you richly; in all wisdom teaching and admonishing one another with psalms, hymns, and spiritual songs, singing with grace in your heart to the Lord.' },
  { book: 'Ephesians', chapter: 6, verseStart: 1, verseEnd: 1,
    kjvText: 'Children, obey your parents in the Lord: for this is right.',
    webText: 'Children, obey your parents in the Lord, for this is right.' },
  { book: 'Romans', chapter: 12, verseStart: 2, verseEnd: 2,
    kjvText: 'And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.',
    webText: "Don't be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God." },
  { book: 'Philippians', chapter: 4, verseStart: 13, verseEnd: 13,
    kjvText: 'I can do all things through Christ which strengtheneth me.',
    webText: 'I can do all things through Christ, who strengthens me.' },
  { book: 'Philippians', chapter: 4, verseStart: 6, verseEnd: 7,
    kjvText: 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.',
    webText: 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.' },
  { book: 'Proverbs', chapter: 3, verseStart: 5, verseEnd: 6,
    kjvText: "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
    webText: "Trust in Yahweh with all your heart, and don't lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight." },
  { book: 'Jeremiah', chapter: 29, verseStart: 11, verseEnd: 11,
    kjvText: 'For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.',
    webText: 'For I know the thoughts that I think toward you, says Yahweh, thoughts of peace, and not of evil, to give you hope and a future.' },
  { book: 'Joshua', chapter: 1, verseStart: 9, verseEnd: 9,
    kjvText: 'Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.',
    webText: "Haven't I commanded you? Be strong and courageous. Don't be afraid. Don't be dismayed, for Yahweh your God is with you wherever you go." },
  { book: 'Isaiah', chapter: 41, verseStart: 10, verseEnd: 10,
    kjvText: 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.',
    webText: "Don't you be afraid, for I am with you. Don't be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness." },
  { book: 'Psalm', chapter: 23, verseStart: 1, verseEnd: 1,
    kjvText: 'The LORD is my shepherd; I shall not want.',
    webText: 'Yahweh is my shepherd: I shall lack nothing.' },
  { book: 'Psalm', chapter: 46, verseStart: 1, verseEnd: 1,
    kjvText: 'God is our refuge and strength, a very present help in trouble.',
    webText: 'God is our refuge and strength, a very present help in trouble.' },
  { book: 'Matthew', chapter: 6, verseStart: 33, verseEnd: 33,
    kjvText: 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.',
    webText: "But seek first God's Kingdom, and his righteousness; and all these things will be given to you as well." },
  { book: 'Galatians', chapter: 2, verseStart: 20, verseEnd: 20,
    kjvText: 'I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.',
    webText: 'I have been crucified with Christ, and it is no longer I who live, but Christ living in me. That life which I now live in the flesh, I live by faith in the Son of God, who loved me and gave himself up for me.' },
  { book: '2 Timothy', chapter: 1, verseStart: 7, verseEnd: 7,
    kjvText: 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.',
    webText: "For God didn't give us a spirit of fear, but of power, love, and self-control." },
  { book: 'James', chapter: 1, verseStart: 5, verseEnd: 5,
    kjvText: 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.',
    webText: 'But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him.' },
  { book: '1 John', chapter: 1, verseStart: 9, verseEnd: 9,
    kjvText: 'If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.',
    webText: 'If we confess our sins, he is faithful and righteous to forgive us the sins and to cleanse us from all unrighteousness.' },
  { book: 'Romans', chapter: 10, verseStart: 9, verseEnd: 9,
    kjvText: 'That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.',
    webText: 'That if you will confess with your mouth the Lord Jesus, and believe in your heart that God raised him from the dead, you will be saved.' },
  { book: 'Ephesians', chapter: 2, verseStart: 8, verseEnd: 9,
    kjvText: 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast.',
    webText: 'For by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, that no one would boast.' },
  { book: 'Hebrews', chapter: 11, verseStart: 1, verseEnd: 1,
    kjvText: 'Now faith is the substance of things hoped for, the evidence of things not seen.',
    webText: 'Now faith is assurance of things hoped for, proof of things not seen.' },
  { book: 'Proverbs', chapter: 22, verseStart: 6, verseEnd: 6,
    kjvText: 'Train up a child in the way he should go: and when he is old, he will not depart from it.',
    webText: 'Train up a child in the way he should go, and when he is old he will not depart from it.' },
  { book: 'Psalm', chapter: 119, verseStart: 11, verseEnd: 11,
    kjvText: 'Thy word have I hid in mine heart, that I might not sin against thee.',
    webText: 'I have hidden your word in my heart, that I might not sin against you.' },
  { book: '1 Peter', chapter: 5, verseStart: 7, verseEnd: 7,
    kjvText: 'Casting all your care upon him; for he careth for you.',
    webText: 'casting all your worries on him, because he cares for you.' },
  { book: 'Psalm', chapter: 27, verseStart: 1, verseEnd: 1,
    kjvText: 'The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?',
    webText: 'Yahweh is my light and my salvation. Whom shall I fear? Yahweh is the strength of my life. Of whom shall I be afraid?' },
  { book: 'Deuteronomy', chapter: 6, verseStart: 5, verseEnd: 5,
    kjvText: 'And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.',
    webText: 'You shall love Yahweh your God with all your heart, with all your soul, and with all your strength.' },
  { book: 'Matthew', chapter: 5, verseStart: 16, verseEnd: 16,
    kjvText: 'Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.',
    webText: 'Even so, let your light shine before men, that they may see your good works, and glorify your Father who is in heaven.' },
  { book: 'John', chapter: 14, verseStart: 6, verseEnd: 6,
    kjvText: 'Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.',
    webText: 'Jesus said to him, "I am the way, the truth, and the life. No one comes to the Father, except through me."' },
  { book: 'Romans', chapter: 3, verseStart: 23, verseEnd: 23,
    kjvText: 'For all have sinned, and come short of the glory of God.',
    webText: 'for all have sinned, and fall short of the glory of God.' },
  { book: 'Romans', chapter: 6, verseStart: 23, verseEnd: 23,
    kjvText: 'For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.',
    webText: 'For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.' },
  { book: '1 Corinthians', chapter: 10, verseStart: 13, verseEnd: 13,
    kjvText: 'There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it.',
    webText: 'No temptation has taken you except what is common to man. God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make the way of escape, that you may be able to endure it.' },
  { book: '2 Corinthians', chapter: 5, verseStart: 17, verseEnd: 17,
    kjvText: 'Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.',
    webText: 'Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.' },
  { book: 'Ephesians', chapter: 4, verseStart: 32, verseEnd: 32,
    kjvText: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
    webText: 'And be kind to one another, tenderhearted, forgiving each other, just as God also in Christ forgave you.' },
  { book: 'Philippians', chapter: 4, verseStart: 8, verseEnd: 8,
    kjvText: 'Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.',
    webText: 'Finally, brothers, whatever things are true, whatever things are honorable, whatever things are just, whatever things are pure, whatever things are lovely, whatever things are of good report: if there is any virtue and if there is any praise, think about these things.' },
  { book: 'Psalm', chapter: 34, verseStart: 8, verseEnd: 8,
    kjvText: 'O taste and see that the LORD is good: blessed is the man that trusteth in him.',
    webText: 'Oh taste and see that Yahweh is good. Blessed is the man who takes refuge in him.' },
  { book: 'Psalm', chapter: 139, verseStart: 14, verseEnd: 14,
    kjvText: 'I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.',
    webText: 'I will give thanks to you, for I am fearfully and wonderfully made. Your works are wonderful. My soul knows that very well.' },
  { book: 'Micah', chapter: 6, verseStart: 8, verseEnd: 8,
    kjvText: 'He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?',
    webText: 'He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?' },
  { book: 'Matthew', chapter: 11, verseStart: 28, verseEnd: 28,
    kjvText: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
    webText: 'Come to me, all you who labor and are heavily burdened, and I will give you rest.' },
  { book: 'Romans', chapter: 5, verseStart: 8, verseEnd: 8,
    kjvText: 'But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.',
    webText: 'But God commends his own love toward us, in that while we were yet sinners, Christ died for us.' },
]
